### ISSUE TITLE
Product Template Error

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#135]
Craft CMS 3.0.0-RC15
Commerce Ref: e3a8f83656a0c7de7e37bf85d418606cf7e23d3e

I'm having an issue where I can't view products on the front-end. I've updated the template used for all of my product types a number of times, and randomly it will change the template to use `{productType.handle}/_category` instead (I can't figure out what is triggering the change of the template). The link to view the front-end of the product disappears as well. When those links are present, I can click them and they go to a 404 saying the template can't be found, but it definitely exists.

Here's a screencast of some of the weirdness:
https://drive.google.com/file/d/1nnLcuJ-pE97rsnccf0dXpyZCIbJ8UP35/view?usp=sharing

**Comment by lukeholder** [comment]
Thanks for reporting! `composer update` and it should be fixed. Thanks!

**Comment by davist11** [comment]
Hmm, I'm still having the same 404 template not found issue after updating Commerce. Screen recording:

https://drive.google.com/file/d/1lj7ol67WhM2L41Ms8wagzN2s8mhk7pBT/view?usp=sharing

**Comment by lukeholder** [comment]
Thanks for reporting! @davist11 `composer update` and it should be fixed. Thanks!
