### ISSUE TITLE
Status change message copied from previous status

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1366]
### Description

When changing an order's status from the CP order edit page, the previous order status message is copied into the message text area.

### Steps to reproduce

1. Start on a CP order edit page for an order where the current status has a message.
2. Click Edit, then change the status to a new one. The message from the previous status is copied into the text area provided for the new status message.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.1

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for bringing this to our attention, we have pushed a fix that will be included in the next release.

Thanks.

**Comment by ryanmwc** [comment]
@nfourtythree I am still seeing this bug. 

![order-status-message-duplication](https://user-images.githubusercontent.com/59359516/85957699-ddbf8700-b98f-11ea-9f04-4a0602d9482a.gif)

### Additional info
- Craft version: 3.4.25
- Plugins & versions: Commerce 3.1.10

**Comment by nfourtythree** [comment]
Hi @ryanmwc 

Thank you for bringing this to our attention. We have pushed a fix for this that will be included in the next release.

Thanks!
