### ISSUE TITLE
Duplicate addresses saved

### ISSUE THREAD

**Issue by jameslindeman** [craftcms/commerce#1395]
### Description

If a duplicate address is entered at checkout Commerce saves it as a new address.

### Steps to reproduce

1. Use the example templates, add something to cart and checkout
2. Go to the address section of the process
3. Enter an address if none saved, or opt to add a new address and enter a duplicate
4. Save and move to the next page but then go back using the browser’s back button
5. Resubmit the same address
6. Refresh the address page to see the saved duplicate addresses

### Additional info

I think there’s a case for checking for duplicates. Although the scenario with the example templates might not happen often, duplicates can be more common with different checkout designs/processes.  If duplicates were caught front-end forms could be simplified in some cases.  

I started to try and patch this with a plugin but hit a hurdle trying to save the matched address to the cart: https://craftcms.stackexchange.com/questions/35063/update-cart-s-address-id-from-plugin

- Craft Commerce version: 3.1.2

**Comment by lukeholder** [comment]
Believe this was fixed in https://github.com/craftcms/commerce/issues/1435

**Comment by iamtompickering** [comment]
Just come across this as I am hitting the same issue. 

I even dropped in the example templates as I thought it could have been a templating issue on my end, but what @jameslindeman has described happens in the example templates too. 

Any chance you'd be able to reopen this and take a look @lukeholder?

Commerce Version: 3.1.12
Craft Version: 3.4.29.1

**Comment by jameslindeman** [comment]
I’m also still seeing this. And, although maybe a separate thing, I’ve noticed payment methods are also being duplicated if the same card is submitted.
