### ISSUE TITLE
Receiving deprecation error for EVENT_BEFORE_MATCH_LINE_ITEM

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1481]
**Description**
I'm getting the deprecation error below

```
Deprecation error: Discounts::EVENT_BEFORE_MATCH_LINE_ITEM has been deprecated. Use Discounts::EVENT_DISCOUNT_MATCHES_LINE_ITEM instead.
```
and it seems to be coming from a craft commerce file outside of my control (in the vendor directory)

stack trace
```
19 | Deprecation error: Discounts::EVENT_BEFORE_MATCH_LINE_ITEM has been deprecated. Use Discounts::EVENT_DISCOUNT_MATCHES_LINE_ITEM instead.From: D:\myfiles\laragon\www\mydirectory\vendor\craftcms\commerce\src\services\Discounts.php (494)
-- | --
craft\commerce\services\Discounts::matchLineItem(craft\commerce\models\LineItem, craft\commerce\models\Discount, true)From: D:\myfiles\laragon\www\mydirectory\vendor\craftcms\commerce\src\models\LineItem.php (621)
craft\commerce\models\LineItem::populateFromPurchasable(craft\commerce\elements\Variant)From: D:\myfiles\laragon\www\mydirectory\vendor\craftcms\commerce\src\models\LineItem.php (579)
craft\commerce\models\LineItem::refreshFromPurchasable()From: D:\myfiles\laragon\www\mydirectory\vendor\craftcms\commerce\src\elements\Order.php (1551)
```

**To Reproduce**
1. add an item to cart

**Additional info**
- Craft version: 3.1.5
- PHP version: 7.4

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#ff96012d948da252b5388d1462fce6b298a5974d as 3.1.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by RitterKnightCreative** [comment]
Still getting a variation of this but in 3.1.10. Looks like the ElementAPI is calling it but guessing that's not really the problem?
```

22 | Deprecation error: Discounts::EVENT_BEFORE_MATCH_LINE_ITEM has been deprecated. Use Discounts::EVENT_DISCOUNT_MATCHES_LINE_ITEM instead.  Called from /vendor/craftcms/commerce/src/services/Discounts.php:497
-- | --
21 | craft\commerce\services\Discounts::matchLineItem(craft\commerce\models\LineItem, craft\commerce\models\Discount, false)  Called from /vendor/craftcms/commerce/src/services/Discounts.php:571
20 | craft\commerce\services\Discounts::matchOrder(craft\commerce\elements\Order, craft\commerce\models\Discount)  Called from /vendor/craftcms/commerce/src/adjusters/Discount.php:111
19 | craft\commerce\adjusters\Discount::adjust(craft\commerce\elements\Order)  Called from /vendor/craftcms/commerce/src/elements/Order.php:1577
18 | craft\commerce\elements\Order::recalculate()  Called from /vendor/craftcms/commerce/src/elements/Order.php:1638
17 | craft\commerce\elements\Order::afterSave(false)  Called from /vendor/craftcms/cms/src/services/Elements.php:2169
16 | craft\services\Elements::_saveElementInternal(craft\commerce\elements\Order, false, false, true)  Called from /vendor/craftcms/cms/src/services/Elements.php:531
15 | craft\services\Elements::saveElement(craft\commerce\elements\Order, false)  Called from /vendor/craftcms/commerce/src/services/Carts.php:107
14 | craft\commerce\services\Carts::getCart(true)  Called from /config/element-api.php:15
13 | craft\services\Config::{closure}()
12 | ReflectionFunction::invokeArgs([])  Called from /vendor/craftcms/element-api/src/controllers/DefaultController.php:251
11 | craft\elementapi\controllers\DefaultController::_callWithParams(Closure, ["pattern" => "cart.json"])  Called from /vendor/craftcms/element-api/src/controllers/DefaultController.php:85
10 | craft\elementapi\controllers\DefaultController::actionIndex("cart.json")
9 | call_user_func_array([craft\elementapi\controllers\DefaultController, "actionIndex"], ["cart.json"])  Called from /vendor/yiisoft/yii2/base/InlineAction.php:57
8 | yii\base\InlineAction::runWithParams(["pattern" => "cart.json", "p" => "cart.json"])  Called from /vendor/yiisoft/yii2/base/Controller.php:157
7 | craft\elementapi\controllers\DefaultController::runAction("", ["pattern" => "cart.json", "p" => "cart.json"])  Called from /vendor/craftcms/cms/src/web/Controller.php:178
6 | craft\elementapi\controllers\DefaultController::runAction("", ["pattern" => "cart.json", "p" => "cart.json"])  Called from /vendor/yiisoft/yii2/base/Module.php:528
5 | craft\web\Application::runAction("element-api", ["pattern" => "cart.json", "p" => "cart.json"])  Called from /vendor/craftcms/cms/src/web/Application.php:291
4 | craft\web\Application::runAction("element-api", ["pattern" => "cart.json", "p" => "cart.json"])  Called from /vendor/yiisoft/yii2/web/Application.php:103
3 | craft\web\Application::handleRequest(craft\web\Request)  Called from /vendor/craftcms/cms/src/web/Application.php:276
2 | craft\web\Application::handleRequest(craft\web\Request)  Called from /vendor/yiisoft/yii2/base/Application.php:386
1 | craft\web\Application::run()  Called from /web/index.php:21


```
