### ISSUE TITLE
Deprecation warning/error getAvailableShippingMethods()

### ISSUE THREAD

**Issue by Bavixke** [craftcms/commerce#1508]
**Description**
I'm getting the following deprecation warning/error:
`Order::getAvailableShippingMethods() has been deprecated. Use Order::getAvailableShippingMethodOptions().`

**To Reproduce**
1. Set 'throwExceptions' for deprecator in app.php 
2. Go to order detail in CP (/admin/commerce/orders/{id})

**Expected behavior**
Viewing order detail without the deprecation warning/errror.

**Additional info**
- Craft version: 3.4.23
- PHP version: 7.3.17
- Database driver & version: MySQL 5.7.29
- Plugins & versions: Craft Commerce 3.1.8

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#d639a89c15d404fcda53230827dd282504eb8aa0 as 3.1.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Bavixke** [comment]
I'm sorry but I'm still getting the warning/error.

**Comment by Bavixke** [comment]
@lukeholder The issue is still there. The warning/error returns in both the CP and the front-end (saving shipping method).

**Comment by davidhellmann** [comment]
I also get the error and with: 
```
'deprecator' => [
  'throwExceptions' => YII_DEBUG,
],
```

my JS add to cart does not work.
