### ISSUE TITLE
Default templates - prepend URL of static files with base site address

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1808]
Right now files are linked like this:

```
    <link rel="stylesheet" href="/shop/style.css">
```
Which means that if site is in some subdirectory on server, brower looks for `domain.com/shop/style` instead of `domain.com/subdirectory/web/shop/style.css`.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

The latest example templates inline all the CSS required in a `style` tag in the `head` of the HTML.

Are you using the latest templates?

Thanks

**Comment by piotrpog** [comment]
@nfourtythree 
My bad, i was indeed using old template. But while we are at it, same error occurs in new template - in cart widget links. Addresses in buttons on bottoms of widgets.

![image](https://user-images.githubusercontent.com/42622545/97216640-6fb49080-17c6-11eb-8018-07c706068057.png)

**Comment by lukeholder** [comment]
@pdaleramirez Can you update all example templates files in `example-templates/*` to use the `url()` twig function: https://craftcms.com/docs/3.x/dev/functions.html#url

anywhere we have a link e.g:

https://github.com/craftcms/commerce/blob/develop/example-templates/shop/_includes/floating-cart.twig#L32

Ensuring that all the links you change work. Thanks!

**Comment by lukeholder** [comment]
This has been resolved in #1816

**Comment by lukeholder** [comment]
Also, please update to the latest example templates as `<link rel="stylesheet" href="/shop/style.css">` is no longer used.

**Comment by piotrpog** [comment]
Just installed latest version of plugin and copied default templates into `templates` directory. It seems that issue still persists in one place. When order is made, user is redirected to order page, this page has wrong URL:

```
http://localhost/shop/customer/order?number=39d04aa86c96c85298427681308ac3eb&success=true
```

**Comment by nfourtythree** [comment]
Hi @piotrpog 

just pushed an update that fixes the cancel and success redirects.

Thanks!

**Comment by piotrpog** [comment]
@nfourtythree @lukeholder 
I recently checked out example templates and its the same problem all over again. Every URL is outputted without full address, for example "shop/cart" instead of "website.com/shop/cart".

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thanks for pointing this out, looks like we missed a `url()` method in the cart link in the main nav.

We have pushed a fix for that example template, the fix will be included in the next release of Commerce.

Thanks!
