### ISSUE TITLE
Impossible to invoke a method ("createForm") on a null variable.

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#1851]
I've updated Commerce from 3.2.9.1 => 3.2.10.1 (And craft 3.5.14 => 3.5.15.1)

Now, when I click to create a new product, I get this error:

```
Impossible to invoke a method ("createForm") on a null variable.
in /Users/***/Sites/***/vendor/craftcms/commerce/src/templates/products/_variant_matrix_fields.html

...
{% namespace namespace %}
        {{ variant.getFieldLayout().createForm(variant).render()|raw }}
    {% endnamespace %}
...
```

When I want to edit an existing product, everything works fine.

**Comment by lukeholder** [comment]
This has been fixed for the next release.

**Comment by ragnarfrosti** [comment]
I just updated to 3.2.11 and I'm still getting this error when trying to create a new product.

**Impossible to invoke a method ("createForm") on a null variable.**

    {% namespace namespace %}
        {{ variant.getFieldLayout().createForm(variant).render()|raw }}
    {% endnamespace %}

**Comment by antistatic** [comment]
I'm running Craft 3.5.15.1 and Commerce 3.2.11 and the problem still persists

**Comment by pdaleramirez** [comment]
If you did the upgrade and you still encountering the issue. Re-saving your product types in commerce setting would resolve your issue.  We are trying to find out the cause of the issue and will provide a fix for it. @ragnarfrosti  @antistatic

**Comment by antistatic** [comment]
Confirming that this fix resolved our issue.
