### ISSUE TITLE
Order billing address id get's overridden on order complete

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2555]
### Description
The order billing address id is getting overridden with the same id as the shipping address on order complete. This seems to happen around `elements/Order.php` line 1978. Before that it is having the two different snapshots of a customer address.
We updated from Craft 3.5.19.1 Commerce 3.2.14.1 where everything was still okay. With this bug it is also not possible anymore to edit the address in the control panel as it doesn't save there.

### Steps to reproduce
1. Create a new order with billing address the same as shipping address -> 1st address is created
2. Complete the order -> 2nd and 3rd addresses are created as snapshots
3. Debug `elements/Order.php`  line 1978 where `$billingAddress->id` will be the same as `$shippingAddress->id` which causes the override while `$his->billingAddressId` at that point is having the right value

### Additional info

- Craft CMS version: 3.7.13
- Craft Commerce version: 3.3.5.1
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: ...

**Comment by pdaleramirez** [comment]
This should already be fixed https://github.com/craftcms/commerce/issues/2128

**Comment by WHITE-developer** [comment]
Tested it on version 3.3.5.1 as stated above. It is happening on a different place than that the issue you are mentioning.
Tried again on 3.4.3 where it still happens. Here are the different steps/states:

1. Item added to the cart, order created in commerce_orders, no addresses yet
`id, billingAddressId, shippingAddressId, isCompleted, dateOrdered, dateUpdated`
`'1161506', NULL, NULL, '0', NULL, '2021-10-04 13:08:16'`
2. Add a shipping address and billingAddressSameAsShipping -> both shipping and billing ids are the same
`id, billingAddressId, shippingAddressId, isCompleted, dateOrdered, dateUpdated`
`'1161506', '17156', '17156', '0', NULL, '2021-10-04 13:11:30'`
3. Continue and finish checkout -> Addresses are copied to snapshots, but both ids are still the same
_commerce_orders_
`id, billingAddressId, shippingAddressId, isCompleted, dateOrdered, dateUpdated`
`'1161506', '17158', '17158', '1', '2021-10-04 13:12:27', '2021-10-04 13:12:30'`
_commerce_addresses_
`id, firstName, dateCreated, dateUpdated`
`'17158', 'test', '2021-10-04 13:12:27', '2021-10-04 13:12:27'`
`'17157', 'test', '2021-10-04 13:12:27', '2021-10-04 13:12:27'`
`'17156', 'test', '2021-10-04 13:09:10', '2021-10-04 13:09:10'`

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for reporting this bug. The issue was fixed in 6abcfcac143f1082787c74b9034b8a086ec4830f and will be included in the next release of Commerce.

To get this early, change your `craftcms/Commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#6abcfcac143f1082787c74b9034b8a086ec4830f as 3.4.3",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by boboldehampsink** [comment]
@nfourtythree I'm seeing customers that have saved 4 addresses on a guest checkout with this change. Is there any chance this keeps on saving new addresses?

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

The changes related to this were only in regards to making sure that addresses are copied to an order correctly on completion. This would leave the original (pre copied address) associated to the customer. Are the addresses all the same? Are they potentially being resaved during the checkout process (maybe without the `id` being populated)?

Thanks.

**Comment by boboldehampsink** [comment]
I'm seeing that there are empty order adresses, while the order customer also has filled adresses attached to them. The id is populated though on the checkout process.

**Comment by nfourtythree** [comment]
Just in case anyone is following along with this, @boboldehampsink 's issue was resolved through the support channel and ended up being related to code in a custom module.
