### ISSUE TITLE
[4.x]: Cannot change site within product

### ISSUE THREAD

**Issue by vandres** [craftcms/commerce#2971]
### Description

This might be related to https://github.com/craftcms/commerce/issues/2920

Before the fix for that issue, the selected site was not respected when going from list to detail view of a product.

Now there seems to be a problem, when trying to change the site within the product detail view.

### Steps to reproduce

1. Create a multi-site project
2. Create a product
3. Try to change the site within the product

### Expected behavior

Site changes

### Actual behavior

Site stays the same

### Craft CMS version

4.2.4

### Craft Commerce version

4.1.2

### PHP version

8.1

### Operating system and version

MacOS, Debian Docker

### Database type and version

MariaDB 10.5

### Image driver and version

-

### Installed plugins and versions

```
  "require": {
    "craftcms/cms": "^4.2.0.2",
    "craftcms/commerce": "^4.1.0",
    "craftcms/commerce-paypal-checkout": "^2.1.0.2",
    "craftcms/redactor": "^3.0",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-vite": "^4.0",
    "php-http/curl-client": "^2.2",
    "putyourlightson/craft-sprig": "^2.1",
    "sebastianlenz/linkfield": "^2.1",
    "spatie/craft-ray": "^2.0",
    "spicyweb/craft-neo": "^3.2",
    "typesense/typesense-php": "^4.8",
    "vaersaagod/geomate": "^2.0",
    "verbb/expanded-singles": "^2.0",
    "verbb/field-manager": "^3.0",
    "verbb/tablemaker": "^4.0",
    "verbb/wishlist": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "deployer/deployer": "^7.0",
    "roave/security-advisories": "dev-master",
    "yiisoft/yii2-shell": "^2.0.3"
  },
  ```

**Comment by nfourtythree** [comment]
Hi @vandres 

Thank you for bringing this to our attention.

We have pushed a fix which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#16fc7a08f3fd8ad257f6e4f9c0e61da3d9b680a4 as 4.1.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks.

**Comment by tmjoen** [comment]
Hi @nfourtythree, this still does not work for me even after installing the dev-develop fix:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/10501945/193019523-2bd9fefc-ba6c-4c2d-9804-f126fff3e1f4.png">

<img width="933" alt="image" src="https://user-images.githubusercontent.com/10501945/193019774-1ffeda6e-e735-4502-a60b-a52d8c984b8d.png">

The "qbEn" link has `?site=qbNo` at the end so the english version never loads. If I manually switch out `?site=qbNo` to `?site=qbEn` in the title bar, the correct version loads.

**Comment by nfourtythree** [comment]
HI @tmjoen 

I have just double-checked this and it appears to still be working as expected, see: https://p191.p3.n0.cdn.getcloudapp.com/items/4guePZY0/7aca5719-c431-4be1-80e7-0f9558f0ee1b.gif?v=425b5e11f075150571bf23512a9e578e

I can see from your video that the URL structure still looks like the old one. Are you up to date with Craft? Have you tried clearing the compiled templates?

Thanks

**Comment by tmjoen** [comment]
My apologies, clearing the compiled templates worked (TIL). Thanks for the quick reply <3
