### ISSUE TITLE
[4.x]: Formatting locale for PDFs

### ISSUE THREAD

**Issue by jakobhaerter** [craftcms/commerce#3145]
### Description
When setting a specific language in the PDF config, Commerce will still use the formatting locale set by the individual user. I'd expect a forced formatting locale based on the language I set in the PDF config.

### Steps to reproduce

1. Create a PDF template and set the language to `German`
2. Make sure your user language is set to `English`
3. Render a PDF and check date or currency properties

### Craft CMS version

4.4.4

### Craft Commerce version

4.2.5.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @jakobhaerter 

Thank you for bringing this issue to our attention.

We have just pushed a new version of Commerce (`4.2.8`) which includes a fix for the issue.

Thanks!

**Comment by wmdhosting** [comment]
I still.  have some issues show some HIGH-ASCII chars..  on PDF: 
![Snag_2845e7f](https://github.com/craftcms/commerce/assets/76176291/d26e7463-3b99-41f5-bc5e-919ae3c5fb5e)

**Comment by wmdhosting** [comment]
I still have issues  showing soem HIGH-ASCII chars.. on PDF:. 
![Snag_2850b59](https://github.com/craftcms/commerce/assets/76176291/a1837f5f-47ec-4695-b897-824c49e26c38)
