### ISSUE TITLE
Tax zone info doesn't update immediately after country change

### ISSUE THREAD

**Issue by fabianhijlkema** [craftcms/commerce#327]
### Description
I'm using VueJS + Axios to update the address data for an order in progress. When I update the shipping country to one that has another Tax Rate, the tax information isn't updated immediately, although the country data is properly updated.

Only after updating some other information in a separate POST call (like the City, or update a Line item) the tax zone is updated as expected.

### Additional info

- Craft version: V3 (latest update)
- PHP version: 7.1.8
- Database driver & version: InnoDB
- Plugins & versions: Commerce V2 (latest update)

**Comment by lukeholder** [comment]
How are you updating the address, through the update-cart controller action?

**Comment by fabianhijlkema** [comment]
Yes, my actions parameter is set to '/commerce/cart/update-cart', and it updates all the data just fine.

I've set up two fictional Tax zones and rates, one for the Netherlands of 21% and one for Bermuda with 5%. Also the shipping cost change from free (the Netherlands) to €8.00 (Bermuda). I set my shipping data to the Netherlands and everything seems fine, then I change my country to Bermuda, and only shipping costs change, but not taxes. Then I adjust the city name to something else, and taxes get adjusted afterwards.

<img width="1074" alt="screen shot 2018-04-24 at 10 41 33" src="https://user-images.githubusercontent.com/2919995/39176699-baf1cdba-47ad-11e8-986f-c11f75a2f40a.png">

<img width="1076" alt="screen shot 2018-04-24 at 10 45 41" src="https://user-images.githubusercontent.com/2919995/39176707-c107beda-47ad-11e8-84f3-d417ed8805c6.png">

<img width="1075" alt="screen shot 2018-04-24 at 10 47 01" src="https://user-images.githubusercontent.com/2919995/39176716-c50e97ec-47ad-11e8-8d3d-331a8d31c671.png">

Does this give you enough information to check it out? Or to see if I'm missing something?


***
I'm setting the following parameters:
billingAddress[id]
billingAddress[firstName]
billingAddress[lastName]
billingAddress[zipCode]
billingAddress[phone]
billingAddress[city]
billingAddress[address1]
billingAddress[countryId]

shippingAddress[id]
shippingAddress[firstName]
shippingAddress[lastName]
shippingAddress[zipCode]
shippingAddress[city]
shippingAddress[address1]
shippingAddress[countryId]
shippingMethodHandle

**Comment by lukeholder** [comment]
Just to be clear,  are you are editing addresses on the CP's Order Edit page by clicking 'edit' in those screenshots?

That will not recalculate the order since it is using a different controller action (it only edits the address, and doesn't resave/recalc the order). Also when editing addresses from that screen, the addresses changes and the page doesn't reload the page so the items on the left wouldn't change.

If you are changing the addresses on the front end templates and using the update-cart are you using zones which include states?

**Comment by lukeholder** [comment]
Can you please email your DB dump to support@craftcommerce.com so I can take a look at all tax rate rules etc. Please reference this issue number in the email. Thanks. @fabianhijlkema

**Comment by fabianhijlkema** [comment]
@lukeholder did the DB dump give you sufficient information?

**Comment by lukeholder** [comment]
Hi @fabianhijlkema has this been resolved in the latest release?

**Comment by lukeholder** [comment]
DB: https://app.frontapp.com/open/cnv_sp2eeb

**Comment by fabianhijlkema** [comment]
Hi Luke, as far as I can see the issue persists. If there is any difference, it is that the changed shipping costs doesn't seem to show up in de backend (although I do get them in the response object on the frontend).

**Comment by lukeholder** [comment]
Is this still an issue? If so I think this is related to https://github.com/craftcms/commerce/issues/422
