### ISSUE TITLE
[4.x]: Rendering bugs on Discounts index page

### ISSUE THREAD

**Issue by elivz** [craftcms/commerce#3457]
### Description

There are a number of bugs on the Discounts admin page of Commerce 4:

1. The `>` on [line 138](https://github.com/craftcms/commerce/blob/77a31641c7294c91d836bea2aac12fd6b06e6fe3/src/controllers/DiscountsController.php#L138) should instead be a `.`. Otherwise if there are date restrictions on a discount, the duration appears as `false` rather than the actual dates.
2. Once that is fixed, the dates are not rendered correctly due to it using the wrong format for the date formatting string. [Line 136](https://github.com/craftcms/commerce/blob/77a31641c7294c91d836bea2aac12fd6b06e6fe3/src/controllers/DiscountsController.php#L136) needs `Locale::FORMAT_PHP` as the final parameter.
3. If a discount is disabled it appears in bold without the usual white circle indicator. I haven't managed to track down the cause of this...seems like it is using a different renderer for the name column when the item is disabled but I don't see an obvious reason why. This issue is also showing up on the Sales index, although the dates _do_ display correctly there.

### Craft CMS version

4.8.9

### Craft Commerce version

4.5.3

**Comment by lukeholder** [comment]
Thanks for reporting this. Those issue are fixed for the next release: https://github.com/craftcms/commerce/pull/3460

I can't seem to reproduce the rendering issue for a disables discount:

![CleanShot 2024-04-22 at 14 40 43@2x](https://github.com/craftcms/commerce/assets/133571/7f78c76c-0b37-483f-ad55-6a92b6e700c1)

Can you please make a new issue if the disabled rendering is still not working for you.

I will put a comment here once the date fix is in a release.

Thanks.

**Comment by nfourtythree** [comment]
This fix has been released as part of Commerce [4.5.4](https://github.com/craftcms/commerce/releases/tag/4.5.4)

Thanks!

**Comment by elivz** [comment]
Thanks! I _am_ still seeing the issue with disabled discounts (and shipping methods), but traced it down to a regression in the VueAdminTable component in Craft core since 4.7.2. I have [reported it over there](https://github.com/craftcms/cms/issues/14861).
