### ISSUE TITLE
[5.x]: Can't switch primary store currency (Unknown column 'elements.dateDeleted')

### ISSUE THREAD

**Issue by mandrasch** [craftcms/commerce#3563]
### Description

I installed craft commerce v5, played around a bit and wanted to switch my primary store currency to EUR. I deleted all inactive carts and orders, also deleted the trashed ones in order to do so (permanently). Also ran `ddev craft gc`.

When I try switching from USD to EUR, I get 

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause'
The SQL being executed was: SELECT EXISTS(SELECT *
FROM `ri_commerce_orders`
LEFT JOIN `ri_elements` ON `elements`.`id` = `commerce_orders`.`id`
WHERE (`storeId`=1) AND (`elements`.`dateDeleted` IS NULL))
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'elements.dateDeleted' in 'where clause'
)
```

### Steps to reproduce

1. Switch USD to EUR in Commerce > System Settings > Stores > Primary
2. Hit save

![image](https://github.com/craftcms/commerce/assets/777278/78d0f89d-f6f2-4a40-93b6-a1c43d08aa9c)

### Expected behavior

Save successfull

### Actual behavior

MySQL exception

### Craft CMS version

5.2.3

### Craft Commerce version

5.0.11.1

### PHP version

8.2.20

### Operating system and version

Mac OSX / DDEV

### Database type and version

MySQL 8.0

### Installed plugins and versions

-

**Comment by mandrasch** [comment]
Maybe related to https://github.com/craftcms/commerce/issues/3433?

**Comment by lukeholder** [comment]
Thanks for reporting. This is fixed for the next release. 

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#0bf59809c239e1e906b2953cd8937bfec58f9304",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once we cut the next release.

**Comment by nfourtythree** [comment]
Hi

Commerce version `5.0.12` has been released with this update included.

Thanks!

**Comment by mandrasch** [comment]
Hi @lukeholder @nfourtythree, thanks for your responses!

I updated to `5.0.12.2`, but I'm still not able to switch currencies in Shop settings:

![image](https://github.com/user-attachments/assets/e6e7bdd2-78d8-4b21-a7d2-c1ef50bd66a6)

![image](https://github.com/user-attachments/assets/76f0047c-9f1c-4f83-9775-2730756f291e)

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause'
The SQL being executed was: SELECT EXISTS(SELECT *
FROM `ri_commerce_orders`
LEFT JOIN `ri_elements` ON `elements`.`id` = `commerce_orders`.`id`
WHERE (`storeId`=1) AND (`elements`.`dateDeleted` IS NULL))
```

Let me know if I can assist in debugging this, thanks very much!

**Comment by mandrasch** [comment]
Okay, full error log helps:

`in /var/www/html/vendor/craftcms/commerce/src/models/Store.php at line 201– craft\db\Query::exists()`

![image](https://github.com/user-attachments/assets/22d29a7c-017b-4125-8eba-a6468cc5ecf3)

![riff ddev site_admin_commerce_settings_stores_1](https://github.com/user-attachments/assets/e4254f2d-80ae-4f1d-a0c9-c7b963d2aafc)

In release https://github.com/craftcms/commerce/commit/0bf59809c239e1e906b2953cd8937bfec58f9304 another code line was fixed (StoresController)

(I did not test the hotfix but waited for the official release of it)

**Comment by nfourtythree** [comment]
Hi @mandrasch 

Looking at the screenshot you posted from the stack trace:

![](https://private-user-images.githubusercontent.com/777278/348647651-22d29a7c-017b-4125-8eba-a6468cc5ecf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzUxODAsIm5iZiI6MTcyMTAzNDg4MCwicGF0aCI6Ii83NzcyNzgvMzQ4NjQ3NjUxLTIyZDI5YTdjLTAxN2ItNDEyNS04ZWJhLWE2NDY4Y2M1ZWNmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwOTE0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDE1NWYxYjg2MDBmMGYzNzZkODBkYjdlYmRiZGEzNjY0MGRmNDQwM2YxNzAwMjI5YWNjMjFmMTg0OGMyMzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HUhKxIwW55FQlWmKKk8kDElEuCG2Ha4CGeR1_XvdA6A)

It looks like this is the pre-fix code, could you make sure you are up to date with the latest version of Commerce and try again.

Thanks!

**Comment by mandrasch** [comment]
Hi @nfourtythree, 

as far as I see: 

In https://github.com/craftcms/commerce/commit/0bf59809c239e1e906b2953cd8937bfec58f9304, the `src/controllers/StoresController.php` is only fixed - but the error occurs in `models/Store.php at line 201` (https://github.com/craftcms/commerce/blob/5.x/src/models/Store.php#L199)?

```php
                $hasOrders = (new Query())
                    ->from(Table::ORDERS)
                    ->leftJoin(\craft\db\Table::ELEMENTS, '[[elements.id]] = [[commerce_orders.id]]')
                    ->where([
                        'storeId' => $this->id,
                        'elements.dateDeleted' => null,
                    ])
                    ->exists();
```

I should be up-to-date locally:

```
ddev composer show
craftcms/commerce                       5.0.12.2 Craft Commerce

ddev craft project-config/diff
No pending project config YAML changes.

ddev craft migrate
Checking for pending content migrations ...
No new migrations found. Your system is up-to-date.

ddev composer dumpautoload
```

![image](https://github.com/user-attachments/assets/9c858c01-5a66-4377-a2e4-c14e3d4cf486)

**Comment by nfourtythree** [comment]
Hi @mandrasch 

Thanks for the update and the info. Was a strange one as I wasn't actually able to replicate that issue even with that code in place in the store model.

However, we have now applied the fix to the store model and pushed it up. This fix will be included in the next release ofr Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#164e8e8f7c22ce1b3161aa4b5d25c11b32afc93e as 5.0.12.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by mandrasch** [comment]
Hi @nfourtythree, 

thanks very much!

Oh, interesting. 🤔 

Did you try with a database prefix or without a prefix?

My setup uses a prefix: `DB_TABLE_PREFIX=ri_`

Other settings I had locally in `.ddev/config.yaml`:

```
php_version: "8.2"
webserver_type: nginx-fpm
database:
    type: mysql
    version: "8.0"
```

**Comment by mandrasch** [comment]
Regarding hotfix - I used

```bash
ddev composer require  "craftcms/commerce":"5.x-dev#164e8e8f7c22ce1b3161aa4b5d25c11b32afc93e as 5.0.12.2"
ddev composer install
```

Switching the currency worked without an error now (locally).

But the weird thing is, that I see three main currencies listed after deploying 🤔  (I also saw the USD from before, but could delete it)

![image](https://github.com/user-attachments/assets/f23b4859-20cd-460e-939c-1c22176db19f)

Remote database:

![image](https://github.com/user-attachments/assets/c1de509d-1a3a-4a6f-972f-ba9213a8f7e4)

Locally in DDEV - I only see EUR once.

**Comment by lukeholder** [comment]
The fixes above were released in Craft Commerce 5.0.13

If you still have a problem with that release can you please create a new issue with further details.

Thanks!
