### ISSUE TITLE
[5.x]: Multi-Store Inventory not loading

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/commerce#3696]
### What happened?

Inventory seemed to be working okay when I had just one store, but stopped working when I added a second store. The screen just sits there with the spinning loading icon.

I also tried an inventory transfer and got an error:
TypeError
craft\commerce\collections\UpdateInventoryLevelCollection::craft\commerce\collections\{closure}(): Argument #1 ($updateInventoryLevel) must be of type craft\commerce\models\inventory\UpdateInventoryLevel, craft\commerce\models\inventory\UpdateInventoryLevelInTransfer given

### Craft CMS version

Pro 5.4.6

### Craft Commerce version

Pro 5.1.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Hi, could you expand on "The screen just sits there with the spinning loading icon." which screen is that?

Could you send your DB backup, composer.json and composer.lock to support@craftcms.com and reference this issue please? Include the steps to reproduce.

 We can then take a look at trying to reproduce what is causing the issue. Thanks

**Comment by AndrewMac** [comment]
The main Commerce: Inventory screen. I will ask my client about sending the DB, but they have not allowed that in the past.

**Comment by AndrewMac** [comment]
The main Commerce: Inventory screen. I will ask my client about sending the DB, but they have not allowed that in the past.

**Comment by lukeholder** [comment]
No worries, can you run the `php craft gc` and `php craft resave/products` commands and see if that fixes the issue?

**Comment by AndrewMac** [comment]
I ran the gc command without issue, but when I tried "ddev craft resave/products" it told me that "No products exist for that criteria" (resaving entries worked just fine, though?). That's all a bit strange, though, because the same command works okay on a brand-new Craft/Commerce-only site I just set up to test this issue for incompatible plugins. I still get the spinning wheel on the project site, and with the resave command not working I can't see if that fixes things.

I can also report that the inventory screen loads okay on that new Craft/Commerce-only site I just set up. But the inventory transfer is still giving the error. Just to make sure I read the docs correctly: I set up the transfer, then tried to set the transfer to 'pending'. And that's when the TypeError I reported above kicks in.

**Comment by idleog** [comment]
same problem here. when going in cp commerce->products site hangs, I have to restart ddev. 

I ran craft resave/products, makes about 1 product per half an hour...

**Comment by idleog** [comment]
![Image](https://github.com/user-attachments/assets/f10ed948-7c2b-4721-9bf9-d16df40d9063)

**Comment by lukeholder** [comment]
@idleog did you send your db to support@caftcms.com and reference this ticket?

**Comment by idleog** [comment]
I did via wetransfer, but maybe without reference to this ticket. I am resending now again via wetarnsfer a dump with not all products (but still products with variants, causing problems)

**Comment by lukeholder** [comment]
@idleog I have fixed the errors you are seeing for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#cd2a61ab484944af1c318b0eee49472ef5d53e31 as 5.2.7",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by brandonkelly** [comment]
Craft Commerce 5.2.8 is out with that fix. Thanks again!

**Comment by idleog** [comment]
On my environment with MariaDB 10.6, CraftCMS 5.5.5 and Commerce 5.2.8, the bug still exists (not on MariaDB 10.11)

**Comment by lukeholder** [comment]
@idleog can you reproduce on 5.3 and make a new ticket if the issue persists? Thanks.
