### ISSUE TITLE
[5.x]: Integrity constraint violation after updating to 5.2.9/fixing #3805

### ISSUE THREAD

**Issue by gopeter** [craftcms/commerce#3862]
### Description

I want to create a new product (under special circumstances which are described in "Steps to reproduce") but get a "Integrity constraint violation" error once I want to save it.

I did a lot of local debugging and this commit breaks our current shop: https://github.com/craftcms/commerce/commit/cdb042611602110cd18a6216d4032fc6f65a6acb

### Steps to reproduce

1. Create a multi-site (important!) shop
2. Create a product where revisions are enabled (important!)
3. Create a matrix field with a simple entry type. This entry type needs to contain a field which can be translated for each site/site group
4. Add this matrix field to the variant fields of this product and set propagation method to "save everywhere the owner is saved" (important!)

I was also able to reproduce it in the demo shop: https://living-eft-ae150c3.demo.craft.cloud/admin/commerce/products/bike/820960?site=default&draftId=83&fresh=1#tab04-variants (I've added a second test site and a test matrix field called "Settings")

<img width="1131" alt="Image" src="https://github.com/user-attachments/assets/74116be9-f4b0-4525-b801-fea2854ad5fb" />

### Craft CMS version

5.5.9

### Craft Commerce version

\>= 5.2.9

**Comment by lukeholder** [comment]
Thanks for reporting, I am unable to reproduce:

![Image](https://github.com/user-attachments/assets/a86e1f9e-e200-4b5f-91f0-cfae75dc962f)

https://github.com/user-attachments/assets/369a0c8f-b11f-4dc1-a008-61f0ac1471f7

Can you share your logs for the error or turn on devMode and share the screenshot of the error again?

**Comment by gopeter** [comment]
Hi Luke,

maybe it helps if I share credentials for the demo page I've created? (https://living-eft-ae150c3.demo.craft.cloud/admin/commerce/products/bike/820960?site=default&draftId=83&fresh=1#tab04-variants)

Have you enabled revisions for that product type? 

Here's the error:

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`elementactivity`, CONSTRAINT `fk_qzxfqvcndpghknhtivgvqprhbheenhzvhgej` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `elementactivity` (`elementId`, `userId`, `siteId`, `draftId`, `type`, `timestamp`) VALUES (780343, 1, 15, NULL, 'save', '2025-01-24 08:57:15') ON DUPLICATE KEY UPDATE `siteId`=VALUES(`siteId`), `draftId`=VALUES(`draftId`), `timestamp`=VALUES(`timestamp`)
```

![Image](https://github.com/user-attachments/assets/53fa3d52-71fc-469e-bfc4-367fb658f474)

**Comment by lukeholder** [comment]
Looks like an error when dealing with the element activity table which is a core Craft table and not Commerce. I confirm I have revisions on for the product type but still can't reproduce it.

I don't have access to that test site. Could you send in a support ticket with more info and reference this ticket? Thanks.

**Comment by lukeholder** [comment]
Thanks for reporting. This has been fixed for the next release of Commerce (4.8), I will upadate this ticket once the release is out.

**Comment by lukeholder** [comment]
@gopeter can you test this on Commerce 5.3 and if the issue is persisting, send a DB backup, composer.json and composer.lock to support@craftcms.com and we will attempt to reproduce. Please mention this github number in your email.  Thanks!

**Comment by gopeter** [comment]
Hi @lukeholder,
yes, we are still getting this error. Going to send you the backup and composer files today. 

/edit

Files are sent 👍

**Comment by lukeholder** [comment]
This was a bug in Craft CMS, and was fixed in Craft 5.6.11.

Thanks!
