### ISSUE TITLE
[5.x]: Attempt to read property "iso" on null

### ISSUE THREAD

**Issue by vnali** [craftcms/commerce#3919]
### Description
Paying for a cart in the second store with a different currency via CP throws the error.

### Steps to reproduce

- The first store has USD as its primary currency.
- The second store has EUR as its primary currency.
- On the second site and in the second store, create a new order.
- On the second site, go to the Transactions tab.
- Try to pay via CP (the currency is shown as EUR).
-  Submitting the form throws an error: 'Attempt to read property "iso" on null' on this line: https://github.com/craftcms/commerce/blob/2d4b5f4131514abbe91cdd77c4e02b22efa45167/src/services/Transactions.php#L216.

### Expected behavior
- paying the cart via EUR

### Craft CMS version

5.6.11

### Craft Commerce version

5.3.4

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @vnali 

Thank you for bringing this to our attention.

We have just pushed a fix which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.3.4",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce 5.3.5 has been released with this fix included.

Thanks!

**Comment by vnali** [comment]
Sorry @nfourtythree, I wasn't able to test the fix earlier. I can still reproduce this error in version 5.3.5.

**Comment by nfourtythree** [comment]
Hi @vnali 

Thank you for your response and feedback.

We have pushed a further fix for this issue which we hope to merge and get released soon.

Thanks!

**Comment by nfourtythree** [comment]
Hi

The fix mentioned in the previous comment is now on the `5.x` branch and will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.3.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by vnali** [comment]
I tested the latest dev version and it worked.
Thanks!

**Comment by nfourtythree** [comment]
Commerce 5.3.6 has been released with this fix included.

Thanks!
